language: node_js

node_js:
  - node
  - '--lts'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn lint
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
